var Command = function () {
    var DEVICE_UNKNOWN = "DEVICE_UNKNOWN";
    var DEVICE_CONNECTED = "DEVICE_CONNECTED";
    var DEVICE_ALREADY_CONNECTED = "DEVICE_ALLREADY_CONNECTED";
    var DEVICE_DISCONNECTED = "DEVICE_DISCONNECTED";
    var DEVICE_ALREADY_DISCONNECTED = "DEVICE_ALLREADY_DISCONNECTED";
    var DEVICE_INTRODUCED = "DEVICE_INTRODUCED";
    var DEVICE_ALREADY_INTRODUCED = "DEVICE_ALLREADY_INTRODUCED";
    
    //DEVICE REQUESTS
    var CONNECT_DEVICE = "CONNECT_DEVICE";
    var DISCONNECT_DEVICE = "DISCONNECT_DEVICE";
    var INTRODUCING_DEVICE = "INTRODUCING_DEVICE";
    var BUILD_FINGERPRINT = "BUILD_FINGERPRINT";
    var DEVICE_MOVED = "DEVICE_MOVED";
    
    //WEBPAGE REQUESTS
    var GET_CONNECTED_DEVICES = "GET_CONNECTED_DEVICES";
    var GET_POSITIONS = "GET_POSITIONS";
};
